[package]
name = "xdp"
version = "0.1.0"
authors = ["Akshay Narayan <akshayn@mit.edu>"]
edition = "2018"

[dependencies]
libc = "0.2"
failure = "0.1"
nix = "0.13"

[build-dependencies]
bindgen = "0.49.0"
